#pragma once

// Fortnite (Alpha) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_E8F8CFEB4FCE62B2CE9F77882B4B8FE8
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_E8F8CFEB4FCE62B2CE9F77882B4B8FE8_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_7020CDB54BEC6F11B5019AB2C2B7B010
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_7020CDB54BEC6F11B5019AB2C2B7B010_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_6AE906D64F04C622EE1C0E8790E5820F
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_6AE906D64F04C622EE1C0E8790E5820F_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_299693DB477CBC05AE4889A83B54D61E
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_299693DB477CBC05AE4889A83B54D61E_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_B84856674DC3D341B6A967AB48C4F843
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_B84856674DC3D341B6A967AB48C4F843_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_DD85389D4F735CFF4DAB0D8B03A80E8D
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_DD85389D4F735CFF4DAB0D8B03A80E8D_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_3D7160D64CF82FA62E007C8E287941CB
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_3D7160D64CF82FA62E007C8E287941CB_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_0BAFB06848AAF153C2F785B7A824B201
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_0BAFB06848AAF153C2F785B7A824B201_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_A24A52D742E515D37ABCEBBA06AD40BF
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_A24A52D742E515D37ABCEBBA06AD40BF_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_31DE58E34727B030EC7BF9A722FCC2E0
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_31DE58E34727B030EC7BF9A722FCC2E0_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_8F31170749710A529184539B9C872DF7
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_8F31170749710A529184539B9C872DF7_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_E97773C946CDB83E511FB296809C2F36
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_E97773C946CDB83E511FB296809C2F36_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_80A784A14F311E231803D5937B2B55CE
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_80A784A14F311E231803D5937B2B55CE_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_141A04A3488B616F9877A99E18DD3B97
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_141A04A3488B616F9877A99E18DD3B97_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_0F839A7846C7117C22E469B09EFE47A5
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_0F839A7846C7117C22E469B09EFE47A5_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_66A15ACC46ED352F9CB282BAD1D550E9
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendSpacePlayer_66A15ACC46ED352F9CB282BAD1D550E9_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_94788343401C88F30C5D4EB945C0CA4F
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_94788343401C88F30C5D4EB945C0CA4F_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_DF703EF640238D419B071DABC42563A5
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_DF703EF640238D419B071DABC42563A5_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_B2C98E0B467A316ECB3C8EA0E6E240AF
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_B2C98E0B467A316ECB3C8EA0E6E240AF_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_1CC31CBF454EC03468D635A6384834F1
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_1CC31CBF454EC03468D635A6384834F1_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_B834A4CA4C469983FFD920B381F62542
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_BlendListByBool_B834A4CA4C469983FFD920B381F62542_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_4CC244374DC69718662F6FAEBC923553
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_TransitionResult_4CC244374DC69718662F6FAEBC923553_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_LayeredBoneBlend_E94AF4ED4D3DD700085A118EF3986015
struct UHuskyHusk_AnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_HuskyHusk_AnimBlueprint_AnimGraphNode_LayeredBoneBlend_E94AF4ED4D3DD700085A118EF3986015_Params
{
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.BlueprintUpdateAnimation
struct UHuskyHusk_AnimBlueprint_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (CPF_Parm, CPF_ZeroConstructor, CPF_IsPlainOldData)
};

// Function HuskyHusk_AnimBlueprint.HuskyHusk_AnimBlueprint_C.ExecuteUbergraph_HuskyHusk_AnimBlueprint
struct UHuskyHusk_AnimBlueprint_C_ExecuteUbergraph_HuskyHusk_AnimBlueprint_Params
{
	int                                                EntryPoint;                                               // (CPF_Parm, CPF_ZeroConstructor, CPF_IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
